competitor_list = [
"https://www.wechat.com/",
"https://www.facebook.com/",
"https://www.pinterest.com/",
"https://www.snapchat.com/",
"https://www.bytedance.com/en/",
"https://vk.com/?lang=en",
"https://www.linkedin.com/",
"https://www.reddit.com/",
"https://www.tumblr.com/",
"https://www.instagram.com/",
"https://www.tiktok.com/en/",
"https://www.whatsapp.com/",
"https://www.weibo.com/",
"https://parler.com/",
"https://myspace.com/",
"https://foursquare.com/",
"https://qzone.qq.com/"
]